name: ParticleWorkshop
main: sk.tomsik68.particleworkshop.ParticleWorkshopPlugin
version: 0.1
commands:
    pws:
        description: Particle workshop base-command
    pquota:
        description: Display/Manage your particle quota